workflows:
  release:
    name: Release Build
    environment:
      vars:
        FLUTTER_VERSION: 3.41.9  # Ajustez si nécessaire
      flutter: stable
    scripts:
      - name: Décoder le Keystore JKS
        script: |
          echo "Recréation du fichier de clé..."
          echo $KEYSTORE_BASE64 | base64 --decode > android/app/upload-keystore.jks

      - name: Générer local.properties pour Gradle
        script: |
          echo "Génération de local.properties..."
          echo "flutter.sdk=$FCI_FLUTTER_HOME" > android/local.properties
          echo "release.keystore.password=$KEYSTORE_PASSWORD" >> android/local.properties
          echo "release.key.alias=$KEY_ALIAS" >> android/local.properties
          echo "release.key.password=$KEY_PASSWORD" >> android/local.properties

      # - name: Set up google-services.json
      #   script: |
      #     echo "Génération de google-services.json..."
      #     echo $ANDROID_FIREBASE_JSON_BASE64 | base64 --decode > android/app/google-services.json

      - name: Créer le fichier .env
        script: |
          echo "Génération du fichier .env pour le build..."
          echo "API_URL=$API_URL" > .env
          echo "ANOTHER_SECRET_KEY=$ANOTHER_SECRET_KEY" >> .env

      - name: Fix Android SDK 37 directory path
        script: |
          ln -s /usr/local/share/android-sdk/platforms/android-37.0 /usr/local/share/android-sdk/platforms/android-37

      - name: Installer les dépendances
        script: |
          flutter pub get

      - name: Générer les fichiers de build (Build Runner)
        script: |
          dart run build_runner build --delete-conflicting-outputs

      - name: Builder l'APK Release
        script: |
          flutter build apk --release

      - name: Builder l'App Bundle (AAB)
        script: |
          flutter build appbundle --release

      - name: Vérifier la signature
        script: |
          if [ -f "android/app/upload-keystore.jks" ]; then
            echo "✅ Keystore trouvé"
          else
            echo "⚠️ Keystore non trouvé, APK non signé"
          fi

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/bundle/release/*.aab

    publishing:
      email:
        recipients:
          - nixmmobilier@gmail.com
        notify:
          success: true
          failure: true